<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWKt9ECS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWKt9ECS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWKt9ECS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWKt9ECS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWKt9ECS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WKt9ECS',
    'container.build_id' => '4f653080',
    'container.build_time' => 1646319633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWKt9ECS');
